Repository tablexi/nucore-open, pull requests merged in 2018-06, with the labels that each got.

#1570 Split facility sub-items to their own columns
  app/assets/stylesheets/app/product_list.scss
  app/assets/stylesheets/application.scss
  app/controllers/facilities_controller.rb
  app/views/facilities/_product_list.html.haml
  app/views/facilities/show.html.haml
  config/settings.yml
Labels: UConn

#1594 [#139184] Exclude inactive/archived products from available accessories
  app/controllers/product_accessories_controller.rb
  spec/controllers/product_accessories_controller_spec.rb
Labels: NU

#1595 [#139276] Add extra interpolation params to new user email
  app/views/notifier/new_user.html.haml
  app/views/notifier/new_user.text.erb
Labels: NU

#1604 [#139184] Do not exclude hidden products from accessories dropdown
  app/controllers/product_accessories_controller.rb
  spec/controllers/product_accessories_controller_spec.rb
Labels: NU

#1608 [#140359] Fix SAML logout link error
  vendor/engines/saml_authentication/app/controllers/saml_authentication/sessions_controller.rb
Labels: RaDar
