Repository tablexi/nucore-open, pull requests merged in 2018-02, with the labels that each got.

#1395 [#130642] SAML authentication
  Gemfile
  Gemfile.lock
  README.md
  app/views/devise/sessions/new.html.haml
  config/environments/test.rb
  config/initializers/devise.rb
  config/settings.yml
  config/settings/test.yml
  spec/models/external_service/url_service_spec.rb
  vendor/engines/saml_authentication/.gitignore
  vendor/engines/saml_authentication/README.md
  vendor/engines/saml_authentication/app/controllers/saml_authentication/sessions_controller.rb
  vendor/engines/saml_authentication/app/views/saml_authentication/sessions/_new.html.haml
  vendor/engines/saml_authentication/config/locales/en.yml
  vendor/engines/saml_authentication/lib/saml_authentication.rb
  vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
  vendor/engines/saml_authentication/lib/saml_authentication/engine.rb
  vendor/engines/saml_authentication/lib/saml_authentication/model.rb
  vendor/engines/saml_authentication/lib/saml_authentication/routes.rb
  vendor/engines/saml_authentication/lib/saml_authentication/user_locator.rb
  vendor/engines/saml_authentication/lib/saml_authentication/user_updater.rb
  vendor/engines/saml_authentication/lib/saml_authentication/version.rb
  vendor/engines/saml_authentication/saml_authentication.gemspec
  vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
  vendor/engines/saml_authentication/spec/fixtures/idp_metadata.xml
  vendor/engines/saml_authentication/spec/fixtures/login_response.xml
Labels: RaDar

#1396 [#140237] Strong params part 1
  app/controllers/affiliates_controller.rb
  app/controllers/application_controller.rb
  app/controllers/file_uploads_controller.rb
  app/controllers/offline_reservations_controller.rb
  app/controllers/order_imports_controller.rb
  app/controllers/order_statuses_controller.rb
  app/controllers/price_groups_controller.rb
  app/controllers/product_access_groups_controller.rb
  app/controllers/product_accessories_controller.rb
  app/controllers/users_controller.rb
  spec/controllers/affiliates_controller_spec.rb
  spec/controllers/file_uploads_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: UIC

#1388 Fix transaction search N+1s
  app/services/transaction_search/base_optimizer.rb
  app/services/transaction_search/n_plus_one_optimizer.rb
  app/services/transaction_search/searcher.rb
  lib/transaction_search.rb
  vendor/engines/secure_rooms/app/services/secure_rooms/n_plus_one_occupancy_optimizer.rb
  vendor/engines/secure_rooms/lib/secure_rooms/engine.rb
Labels: NU

#1398 Strong params part 2
  app/controllers/account_users_controller.rb
  app/controllers/bundle_products_controller.rb
  app/controllers/facility_account_users_controller.rb
  app/controllers/facility_facility_accounts_controller.rb
Labels: UIC

#1400 Fix ordering of desc nulls first
  lib/nucore.rb
Labels: RaDar

#1404 handle strong params for facility facility accounts sections
  app/controllers/facility_facility_accounts_controller.rb
Labels: UIC

#1408 [#140451] Upgrade LDAP gems
  Gemfile.lock
  vendor/engines/ldap_authentication/ldap_authentication.gemspec
Labels: NU

#1407 [#137156] Redirect to In Review after disputing
  app/controllers/order_details_controller.rb
  app/services/transaction_search/searcher.rb
  config/locales/en.controllers.yml
  config/locales/en.yml
  spec/features/disputing_an_order_spec.rb
Labels: NU

#1412 Support transaction search with strong params enabled
  app/forms/transaction_search/search_form.rb
Labels: UIC

#1411 [#140459] Fix display when no transactions on All Transactions
  app/views/facilities/transactions.html.haml
  app/views/shared/transactions/_top2.html.haml
  config/locales/en.yml
Labels: UIC

#1399 [#140401] Filtering: Replace Send Notifications with new searcher
  app/controllers/facility_notifications_controller.rb
  app/views/facility_notifications/index.html.haml
  app/views/shared/transactions/_search2.html.haml
  spec/controllers/facility_notifications_controller_spec.rb
  spec/features/admin/sending_notifications_spec.rb
Labels: NU

#1402 [#140402] Replace movable_transactions with newer filtering
  app/controllers/facilities_controller.rb
  app/helpers/reassign_chart_strings_helper.rb
  app/views/facilities/confirm_transactions.html.haml
  app/views/facilities/movable_transactions.html.haml
  app/views/facilities/reassign_chart_strings.html.haml
  config/locales/en.yml
  spec/controllers/facilities_controller_spec.rb
  spec/features/admin/moving_transactions_spec.rb
Labels: NU

#1414 [#121458] Fix admin ability to edit past reservations in cart
  app/controllers/reservations_controller.rb
  app/helpers/date_helper.rb
  app/views/orders/_edit_date.html.haml
  lib/ability.rb
  spec/controllers/reservations_controller_spec.rb
  spec/features/placing_an_order_on_behalf_of_spec.rb
  spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
  spec/features/purchasing_a_reservation_spec.rb
Labels: NU

#1416 Fix display of no transactions on movable transactions and send notifications
  app/views/facilities/movable_transactions.html.haml
  app/views/facility_notifications/index.html.haml
Labels: NU

#1401 [#140401] Replace orders in review with new search
  app/controllers/facility_notifications_controller.rb
  app/views/facility_notifications/in_review.html.haml
  spec/controllers/facility_notifications_controller_spec.rb
  spec/features/admin/review_period_spec.rb
Labels: NU

#1419 Strong params part 3
  app/controllers/application_controller.rb
  app/controllers/facility_reservations_controller.rb
  app/controllers/file_uploads_controller.rb
  app/controllers/offline_reservations_controller.rb
  app/controllers/order_detail_stored_files_controller.rb
  app/controllers/product_users_controller.rb
  app/controllers/products_common_controller.rb
  app/controllers/reservations_controller.rb
  app/controllers/users_controller.rb
  app/presenters/order_detail_presenter.rb
  app/services/order_details/param_updater.rb
  app/services/order_details/reconciler.rb
  app/services/price_policy_updater.rb
  app/services/reservation_creator.rb
  app/support/accessories/accessorizer.rb
  lib/quiet_strong_params.rb
  spec/controllers/facility_reservations_controller_spec.rb
  spec/presenters/order_detail_presenter_spec.rb
  spec/services/accessorizer_spec.rb
  vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch_form.rb
Labels: UIC
