Repository tablexi/nucore-open, pull requests merged in 2018-10, with the labels that each got.

#1718 [#142011] Allow global admins to unreconcile orders
  app/controllers/reconcilliations_controller.rb
  app/views/order_management/order_details/_form.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/reconcilliations_controller_spec.rb
Labels: RaDar

#1720 [#143678] Affiliate changes
  app/controllers/affiliates_controller.rb
  app/helpers/affiliates_helper.rb
  app/models/affiliate.rb
  app/views/affiliates/index.html.haml
  app/views/facility_accounts/new.html.haml
  spec/factories/affiliates.rb
Labels: RaDar

#1721 [#137154] Fix problem order email issues
  app/controllers/orders_controller.rb
  app/models/order_detail.rb
  app/services/move_to_problem_queue.rb
  spec/app_support/auto_expire_reservation_spec.rb
  spec/controllers/offline_reservations_controller_spec.rb
  spec/factories/orders.rb
  spec/models/reservation_spec.rb
  vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb
  vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
  vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/order_handler_spec.rb
  vendor/engines/secure_rooms/spec/support/auto_orphan_occupancy_spec.rb
Labels: NU

#1708 [#136151] Ability to charge full reservation cost for cancellation
  app/assets/javascripts/price_policy.js.coffee
  app/models/instrument_price_policy.rb
  app/models/instrument_price_policy_calculations.rb
  app/models/order_detail.rb
  app/presenters/reservation_user_action_presenter.rb
  app/services/cancellation_fee_calculator.rb
  app/services/price_policy_updater.rb
  app/views/facility_user_reservations/index.html.haml
  app/views/price_policies/_price_policy_fields.html.haml
  app/views/reservations/_my_table.html.haml
  app/views/time_based_price_policies/_adjustment_row.html.haml
  app/views/time_based_price_policies/_amount_row.html.haml
  app/views/time_based_price_policies/_price_policy_fields.html.haml
  app/views/time_based_price_policies/_table.html.haml
  config/locales/en.models.yml
  config/locales/en.yml
  config/settings.yml
  db/migrate/20180919211201_add_full_cost_cancellation_to_price_policies.rb
  db/schema.rb
  spec/factories/price_groups.rb
  spec/features/admin/instrument_price_policies_controller_spec.rb
  spec/features/admin/item_price_policies_controller_spec.rb
  spec/features/admin/timed_service_price_policies_controller_spec.rb
  spec/models/instrument_price_policy_calculations_spec.rb
  spec/models/order_detail_spec.rb
  spec/presenters/reservation_user_action_presenter_spec.rb
  spec/services/cancellation_fee_calculator_spec.rb
  vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml
Labels: RaDar

#1729 Update LDAP documentation
  config/ldap.yml.template
  vendor/engines/ldap_authentication/README.md
  vendor/engines/ldap_authentication/lib/ldap_authentication.rb
Labels: NU

#1731 [#143771] Prevent error on invalid dates on Reservation#update
  app/support/reservations/duration_change_validations.rb
  spec/app_support/reservations/duration_change_validations_spec.rb
Labels: RaDar

#1733 [#139203] Add product description to training request page
  app/controllers/training_requests_controller.rb
  app/views/products_common/_description.html.haml
  app/views/products_common/show.html.haml
  app/views/reservations/_documentation.html.haml
  app/views/reservations/new.html.haml
  app/views/training_requests/new.html.haml
  config/locales/en.yml
  config/locales/views/en.products.yml
Labels: RaDar

#1732 [#144271] Fix bulk email in IE
  app/assets/javascripts/application.js
  vendor/assets/javascripts/polyfills.js
  vendor/assets/javascripts/polyfills/array.includes.js
Labels: RaDar

#1734 [#143568] Use Roboto font for PDFs
  app/assets/fonts/Roboto-Bold.ttf
  app/assets/fonts/Roboto-Italic.ttf
  app/assets/fonts/Roboto-License.txt
  app/assets/fonts/Roboto-Regular.ttf
  app/support/example_statement_pdf.rb
  app/support/pdf_font_helper.rb
  app/support/statement_pdf.rb
  app/views/statements/show.pdf.prawn
  config/settings.yml
Labels: NU, RaDar

#1727 Fix columns in order form
  app/assets/stylesheets/app/product_list.scss
  app/views/facilities/show.html.haml
Labels: UConn

#1735 [#136151] Fix test failure when charge_full_price_on_cancellation is turned off
  spec/models/order_detail_spec.rb
Labels: RaDar
