Repository tablexi/nucore-open, pull requests merged in 2018-03, with the labels that each got.

#1394 [#140237] Strong params
  app/controllers/products_common_controller.rb
  config/application.rb
  config/environments/development.rb
  spec/controllers/facility_accounts_controller_spec.rb
  spec/controllers/facility_facility_accounts_controller_spec.rb
  spec/controllers/instruments_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/services/account_builder_spec.rb
Labels: UIC

#1422 [#140279] clean up queries
  app/models/order_detail.rb
  app/models/reservation.rb
  spec/controllers/accounts_controller_spec.rb
Labels: UIC

#1424 rm unused controller action/view
  app/controllers/accounts_controller.rb
  app/views/accounts/transactions_in_review.html.haml
  spec/controllers/accounts_controller_spec.rb
Labels: NU

#1423 [#140767] export raw query bug - disambiguate journals
  app/models/reports/export_raw.rb
Labels: RaDar

#1425 [#139338] cross payment source filtering
  app/controllers/accounts_controller.rb
  app/controllers/order_details_controller.rb
  app/controllers/transactions_controller.rb
  app/presenters/nav_tab/link_collection.rb
  app/views/accounts/index.html.haml
  app/views/notifier/review_orders.html.haml
  app/views/notifier/review_orders.text.erb
  app/views/shared/transactions/_search2.html.haml
  app/views/shared/transactions/_table_inside.html.haml
  app/views/transactions/index.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/features/disputing_an_order_spec.rb
  spec/features/transactions_search_spec.rb
Labels: NU

#1430 [#87522] fix subquery ordering bug in oracle, fix order links in new/inprocess
  app/controllers/concerns/new_inprocess_controller.rb
  app/controllers/facility_notifications_controller.rb
  app/controllers/facility_orders_controller.rb
  app/controllers/facility_reservations_controller.rb
  app/models/order_detail.rb
  vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb
Labels: NU

#1432 oracle dislikes "as" keyword
  app/models/order_detail.rb
Labels: NU

#1438 [#139338] Cross Payment Source bounceback changes
  app/controllers/transactions_controller.rb
  app/views/transactions/index.html.haml
  config/locales/en.yml
Labels: NU

#1428 [#140462] order on behalf of reservation statuses determined by dates
  app/models/order.rb
  app/services/order_purchaser.rb
  spec/controllers/orders_controller_spec.rb
  spec/models/order_spec.rb
Labels: NU

#1433 [#140405] payment source transactions link to main transaction filter page
  app/controllers/accounts_controller.rb
  app/views/accounts/index.html.haml
  app/views/accounts/transactions.html.haml
  app/views/shared/_tabnav_account.html.haml
  config/routes.rb
  spec/controllers/accounts_controller_spec.rb
Labels: NU

#1442 [#140609] Update devise_saml_authenticatable
  Gemfile.lock
Labels: RaDar

#1440 [#87522] update new/inprocess/problem tabs for orders/reservations/occupancies…
  app/controllers/concerns/new_inprocess_controller.rb
  app/controllers/concerns/problem_order_details_controller.rb
  app/forms/transaction_search/search_form.rb
  app/models/order_detail.rb
  app/services/transaction_search/date_range_searcher.rb
  app/services/transaction_search/order_status_searcher.rb
  app/views/shared/transactions/_search2.html.haml
  vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb
Labels: NU

#1444 [#140353] replace problematic test
  spec/controllers/global_search_controller_spec.rb
Labels: RaDar

#1443 [#140080] enable product search without logging in or when acting as
  app/controllers/global_search_controller.rb
  app/views/shared/_nav.html.haml
  app/views/shared/nav/_nav_links.html.haml
  spec/controllers/global_search_controller_spec.rb
Labels: RaDar

#1434 Add settings override for default ruby-saml params
  config/settings.yml
  vendor/engines/saml_authentication/README.md
  vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
Labels: UConn

#1429 [#137627] add links to 10 most recently purchased products to home page
  app/controllers/application_controller.rb
  app/controllers/facilities_controller.rb
  app/helpers/products_helper.rb
  app/models/concerns/users/roles.rb
  app/models/facility.rb
  app/models/product.rb
  app/models/user.rb
  app/services/most_recently_used_searcher.rb
  app/views/facilities/_product_list.html.haml
  app/views/facilities/index.html.haml
  config/locales/views/en.facilities.yml
  spec/models/user_spec.rb
  spec/services/most_recently_used_searcher_spec.rb
Labels: NU

#1452 Update .codeclimate.yml
  .codeclimate.yml
Labels: UIC

#1449 revert rubocop to latest version supported by codeclimate
  Gemfile
  Gemfile.lock
Labels: UIC

#1455 [#137627] recently used products/facilities still works when no logged in user
  app/services/most_recently_used_searcher.rb
  spec/controllers/facilities_controller_spec.rb
Labels: NU

#1453 [#140196, #140197] extract secrets from settings.yml
  app/models/concerns/downloadable_file.rb
  config/initializers/paperclip.rb
  config/secrets.yml.template
  config/settings.local.yml.template
  config/settings.yml
Labels: RaDar, UIC

#1458 [#140608] Fix links from Accounts Receivable
  app/views/facility_accounts/accounts_receivable.html.haml
Labels: NU
