Repository tablexi/nucore-open, pull requests merged in 2018-11, with the labels that each got.

#1752 [#144525] Alphabetize homepage case insensitively
  app/controllers/facilities_controller.rb
  app/helpers/a_z_helper.rb
  spec/helpers/a_z_helper_spec.rb
Labels: RaDar

#1766 [#144715] Fix Daily View Navigation Skipping in Firefox
  app/assets/javascripts/timeline.js
Labels: NU

#1759 [#136546] Allow account membership changes after expiration
  app/controllers/account_users_controller.rb
  app/controllers/facility_account_users_controller.rb
  app/models/account.rb
  app/models/account_user.rb
  app/services/account_role_grantor.rb
  app/views/account_users/new.html.haml
  app/views/facility_account_users/new.html.haml
  config/locales/en.models.yml
  config/locales/models/en.account.yml
  config/locales/views/admin/en.facility_account_users.yml
  config/locales/views/en.account_users.yml
  spec/controller_spec_helper.rb
  spec/controllers/facility_account_users_controller_spec.rb
  spec/controllers/global_search_controller_spec.rb
  spec/factories/users.rb
  spec/models/account_spec.rb
  spec/models/account_user_spec.rb
  spec/models/chart_string_reassignment_form_spec.rb
  spec/rails_helper.rb
Labels: NU

#1750 [#140549] Disable users who were removed from LDAP
  app/controllers/users_controller.rb
  app/models/user.rb
  app/presenters/users/name_presenter.rb
  app/views/users/show.html.haml
  config/locales/en.models.yml
  config/locales/views/admin/en.users.yml
  config/routes.rb
  db/migrate/20180917224024_add_facility_notice.rb
  db/migrate/20181102173232_add_expired_to_users.rb
  db/schema.rb
  lib/ability.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/users.rb
  spec/presenters/users/name_presenter_spec.rb
  vendor/engines/ldap_authentication/config/initializers/log_ldap_searches.rb
  vendor/engines/ldap_authentication/lib/ldap_authentication/user_entry.rb
  vendor/engines/ldap_authentication/lib/tasks/ldap_authentication.rake
Labels: NU

#1767 [#144294] Normalize whitespace in statement PDFs
  app/services/whitespace_normalizer.rb
  app/support/example_statement_pdf.rb
  app/support/statement_pdf.rb
  spec/services/whitespace_normalizer_spec.rb
Labels: RaDar

#1770 [#140549] Retry LDAP queries up to 3 times
  vendor/engines/ldap_authentication/lib/ldap_authentication/user_entry.rb
  vendor/engines/ldap_authentication/spec/ldap_authentication/user_entry_spec.rb
Labels: NU

#1771 Handle survey urls that already have a question mark in them
  app/models/external_service/url_service.rb
  spec/models/external_service/url_service_spec.rb
Labels: NU

#1775 Improve stack traces in failing tests
  spec/rails_helper.rb
Labels: Tech Task

#1773 [#144530] Allow requiring a note when creating price policies
  app/assets/stylesheets/nucore.scss
  app/controllers/price_policies_controller.rb
  app/models/price_policy.rb
  app/services/price_policy_updater.rb
  app/views/price_policies/_common_fields.html.haml
  app/views/price_policies/_price_policy_fields.html.haml
  app/views/price_policies/index.html.haml
  app/views/time_based_price_policies/_price_policy_fields.html.haml
  config/locales/views/admin/en.price_policies.yml
  config/settings.yml
  db/migrate/20181119211456_add_note_to_price_policies.rb
  db/schema.rb
  lib/settings_helper.rb
  spec/factories/price_policies.rb
  spec/features/admin/instrument_price_policies_controller_spec.rb
  spec/features/admin/item_price_policies_controller_spec.rb
  spec/features/admin/timed_service_price_policies_controller_spec.rb
  spec/models/item_price_policy_spec.rb
  spec/models/price_policy_spec.rb
  spec/models/product_spec.rb
  spec/models/service_price_policy_spec.rb
  spec/price_policies_controller_shared_examples.rb
  vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml
  vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb
  vendor/engines/secure_rooms/spec/features/create_a_secure_room_spec.rb
Labels: RaDar
