Repository tablexi/nucore-open, pull requests merged in 2018-09, with the labels that each got.

#1670 [#142448] Cross facility bulk email
  app/controllers/users_controller.rb
  app/models/serializable_facility.rb
  app/views/admin/shared/_tabnav_users.html.haml
  lib/ability.rb
  spec/lib/ability_spec.rb
  vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb
  vendor/engines/bulk_email/app/decorators/bulk_email/job_decorator.rb
  vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb
  vendor/engines/bulk_email/app/models/bulk_email/delivery_form.rb
  vendor/engines/bulk_email/app/services/bulk_email/recipient_searcher.rb
  vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_fields.html.haml
  vendor/engines/bulk_email/app/views/bulk_email/bulk_email/create.html.haml
  vendor/engines/bulk_email/app/views/bulk_email/jobs/show.html.haml
  vendor/engines/bulk_email/spec/controllers/bulk_email/bulk_email_controller_spec.rb
  vendor/engines/bulk_email/spec/features/bulk_emailer_searching_spec.rb
  vendor/engines/bulk_email/spec/services/bulk_email/recipient_searcher_spec.rb
Labels: RaDar

#1680 Tech task: add ability to use merge_describer against a branch that isn't develop
  bin/merge_describer
Labels: Tech Task

#1679 [#143237] Make "account is not open" text localized and overridable
  app/models/account.rb
  app/models/order_detail.rb
  config/locales/models/en.account.yml
Labels: RaDar

#1666 [#136050] Send email notification to facility on cancellation
  app/controllers/order_details_controller.rb
  app/controllers/product_notifications_controller.rb
  app/controllers/products_common_controller.rb
  app/mailers/cancellation_mailer.rb
  app/models/concerns/email_list_attribute.rb
  app/models/instrument.rb
  app/models/product.rb
  app/views/admin/products/_product_fields.html.haml
  app/views/admin/shared/_tabnav_product.html.haml
  app/views/cancellation_mailer/notify_facility.html.haml
  app/views/cancellation_mailer/notify_facility.text.erb
  app/views/product_notifications/edit.html.haml
  app/views/product_notifications/show.html.haml
  app/views/products_common/manage.html.haml
  config/locales/en.models.yml
  config/locales/views/admin/en.product_notifications.yml
  config/locales/views/admin/en.products.yml
  config/locales/views/en.cancellation_mailer.yml
  config/routes.rb
  db/migrate/20180822191538_add_cancellation_notification_to_product.rb
  db/schema.rb
  spec/controllers/order_details_controller_spec.rb
  spec/features/admin/product_notifications_controller_spec.rb
  spec/mailers/previews/cancelation_mailer_preview.rb
  spec/models/concerns/email_list_attribute_spec.rb
Labels: RaDar

#1696 Update where_ids_in query for Rails 5
  lib/nucore.rb
  spec/models/order_detail_spec.rb
Labels: NU, Tech Task

#1695 Fix oracle types in Rails 5
  db/migrate/20180907190857_fix_oracle_timestamps.rb
  db/schema.rb
Labels: NU, Tech Task

#1693 [#143399] Add another column to current rooms dashboard
  vendor/engines/secure_rooms/app/views/secure_rooms/shared/_dashboard_column.html.haml
  vendor/engines/secure_rooms/app/views/secure_rooms/shared/_secure_rooms_dashboard.html.haml
  vendor/engines/secure_rooms/config/locales/en.yml
Labels: NU

#1705 Add `manage-mode` body class when in manage mode
  app/controllers/concerns/nav_tab.rb
  app/views/layouts/application.html.haml
Labels: UConn

#1707 Refactor price policy new/edit views
  app/controllers/instrument_price_policies_controller.rb
  app/helpers/rate_display_helper.rb
  app/views/instrument_price_policies/_adjustment_row.html.haml
  app/views/instrument_price_policies/_amount_row.html.haml
  app/views/price_policies/_price_policy_fields.html.haml
  app/views/time_based_price_policies/_adjustment_row.html.haml
  app/views/time_based_price_policies/_amount_row.html.haml
  app/views/time_based_price_policies/_price_policy_fields.html.haml
  app/views/timed_service_price_policies/_adjustment_row.html.haml
  app/views/timed_service_price_policies/_amount_row.html.haml
  vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml
Labels: RaDar, Tech Task

#1703 [#133770] Facility Notification Banner
  app/assets/javascripts/ckeditor/editor.js
  app/controllers/facilities_controller.rb
  app/inputs/readonly_input.rb
  app/models/facility.rb
  app/views/facilities/_facility_fields.html.haml
  app/views/facilities/manage.html.haml
  app/views/facilities/show.html.haml
  app/views/layouts/application.html.haml
  config/initializers/sanitized_allowed.rb
  config/locales/en.models.yml
  config/locales/views/admin/en.facilities.yml
  config/settings.yml
  db/migrate/20180917224024_add_facility_notice.rb
  db/schema.rb
Labels: RaDar

#1712 [#143505] Fix rendering error on invalid product notifications
  app/controllers/product_notifications_controller.rb
Labels: RaDar

#1643 Changes to typography
  app/assets/fonts/Inter-UI-Bold.woff
  app/assets/fonts/Inter-UI-Bold.woff2
  app/assets/fonts/Inter-UI-Medium.woff
  app/assets/fonts/Inter-UI-Medium.woff2
  app/assets/fonts/Inter-UI-Regular.woff
  app/assets/fonts/Inter-UI-Regular.woff2
  app/assets/stylesheets/app/font.scss
  app/assets/stylesheets/app/order_management.scss
  app/assets/stylesheets/app/typography.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/nucore-variables.scss
  app/controllers/product_notifications_controller.rb
  app/views/facilities/index.html.haml
Labels: UConn
