Repository tablexi/nucore-open, pull requests merged in 2018-05, with the labels that each got.

#1537 [#141569] Prevent start for schedule groups in grace period
  app/support/reservations/validations.rb
  spec/models/reservation_spec.rb
Labels: NU

#1538 Fix time-travel bug in spec
  spec/models/reservation_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/time_travel_helpers.rb
  spec/time_travel_helpers.rb
Labels: NU

#1539 [#137710] Improve schedule group error message
  app/models/reservation.rb
  app/support/reservations/validations.rb
  config/locales/en.models.yml
  spec/models/reservation_spec.rb
Labels: NU

#1542 [#141837] Prevent account managers from suspending users
  app/controllers/users_controller.rb
  lib/ability.rb
  spec/lib/ability_spec.rb
Labels: NU

#1543 [#140939] Add alert banner style and hooks
  app/assets/stylesheets/app/global_alert_banner.scss
  app/assets/stylesheets/application.scss
  app/views/layouts/application.html.haml
Labels: RaDar

#1544 [#141837] Fix ability spec for account managers when `create_users` is turned off
  lib/ability.rb
  spec/lib/ability_spec.rb
Labels: NU, UIC

#1545 [#141665] Support both unix timestamps and iso8601 in calendar endpoint
  app/controllers/reservations_controller.rb
  spec/controllers/reservations_controller_spec.rb
Labels: NU

#1553 [#141837] Remove ability for account managers to edit user details
  lib/ability.rb
  spec/features/admin/managing_user_spec.rb
  spec/lib/ability_spec.rb
Labels: NU

#1558 Add a ViewHook for journal download formats
  app/views/facility_journals/_downloads.html.haml
Labels: UConn

#1561 [#134365] Improve error messaging if an instrument has no schedule rules or price policies
  app/controllers/instruments_controller.rb
  app/controllers/products_common_controller.rb
  app/models/instrument_for_cart.rb
  app/models/product.rb
  app/models/product_for_cart.rb
  app/views/products_common/show.html.haml
  config/locales/models/en.instrument_for_cart.yml
  config/locales/models/en.product_for_cart.yml
  config/locales/views/en.products.yml
  spec/controllers/bundles_controller_spec.rb
  spec/controllers/instruments_controller_spec.rb
  spec/controllers/items_controller_spec.rb
  spec/controllers/services_controller_spec.rb
  spec/models/instrument_for_cart_spec.rb
  spec/models/product_for_cart_spec.rb
  spec/models/product_spec.rb
  spec/support/shared_examples/purchasable_product_shared_examples.rb
Labels: NU

#1568 [#141857] Add note field to CSV exports
  app/models/reports/account_transactions_report.rb
Labels: NU

#1564 [#137466] Enable calendar drag-and-drop by default
  app/assets/javascripts/app/reservation_calendar.js
  app/views/reservations/edit.html.haml
  app/views/reservations/new.html.haml
  config/settings.yml
Labels: NU

#1563 Fix spacing on access list index
  app/views/product_users/index.html.haml
Labels: NU

#1562 [#137474] Handle invalid dates in price policies
  app/assets/javascripts/price_policy.js.coffee
  app/controllers/price_policies_controller.rb
  app/helpers/price_policies_helper.rb
  app/models/price_policy.rb
  app/services/price_policy_builder.rb
  app/services/price_policy_updater.rb
  app/views/price_policies/_dates.html.haml
  app/views/price_policies/_price_policy_fields.html.haml
  app/views/time_based_price_policies/_price_policy_fields.html.haml
  config/locales/en.controllers.yml
  spec/app_support/price_policy_mass_assigner_spec.rb
  spec/factories/price_policies.rb
  spec/models/item_price_policy_spec.rb
  spec/models/order_detail_spec.rb
  spec/models/price_policy_spec.rb
  spec/models/service_price_policy_spec.rb
  spec/price_policies_controller_shared_examples.rb
  vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml
Labels: NU

#1575 Allow SAML engine semi-enabling
  config/settings.yml
  vendor/engines/saml_authentication/lib/saml_authentication/engine.rb
Labels: RaDar

#1559 Allow admin-defined logo in header
  app/assets/stylesheets/app/header.scss
  app/assets/stylesheets/responsive.scss
  app/views/shared/_header.html.haml
  config/settings.yml
Labels: UConn
