Repository tablexi/nucore-open, pull requests merged in 2018-12, with the labels that each got.

#1781 [#145520] Restore ability to have links open in new window
  config/initializers/sanitized_allowed.rb
Labels: RaDar

#1779 Use-Manage Table
  app/assets/stylesheets/nucore-variables.scss
  app/assets/stylesheets/nucore.scss
Labels: UConn

#1790 [#141856] Make "Ordered For" column sortable on New/In Process orders page
  app/assets/stylesheets/nucore.scss
  app/controllers/concerns/new_inprocess_controller.rb
  app/controllers/facility_orders_controller.rb
  app/controllers/facility_reservations_controller.rb
  app/views/facility_orders/index.html.haml
  app/views/facility_reservations/index.html.haml
  vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb
  vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
Labels: NU

#1789 Handle External Service URLs that already contain a question mark
  app/models/external_service/url_service.rb
  spec/models/external_service/url_service_spec.rb
Labels: NU

#1786 Use-Manage Buttons
  app/assets/stylesheets/nucore.scss
Labels: UConn

#1796 [#141977] Prevent double icon in dropdown searches
  app/assets/stylesheets/application.scss
Labels: NU

#1797 [#145115] Add minimum price change reason length for order details
  app/models/order_detail.rb
  spec/controllers/order_management/order_details_controller_spec.rb
  spec/models/reports/export_raw_spec.rb
Labels: RaDar

#1795 Allow JS capybara finders to find upcased labels
  spec/features/placing_an_order_on_behalf_of_spec.rb
Labels: UConn

#1787 Use-Manage Form
  app/assets/stylesheets/nucore.scss
Labels: UConn

#1810 [#144674] Add calculated cost fields to export raw
  app/models/order_detail.rb
  app/models/reports/export_raw.rb
  spec/factories/orders.rb
  spec/models/reports/export_raw_spec.rb
  vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb
  vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Labels: RaDar

#1809 Remove `_on` suffix from settings
  config/settings.yml
  lib/settings_helper.rb
  spec/helpers/settings_helper_spec.rb
  spec/rails_helper.rb
Labels: Tech Task

#1811 [#144522] Fix bundle column on export raw
  app/models/order_detail.rb
  app/models/reports/export_raw.rb
  spec/models/reports/export_raw_spec.rb
Labels: RaDar

#1788 Add support for multiple favicons
  app/presenters/favicon_presenter.rb
  app/views/shared/_favicons.html.haml
  app/views/shared/_head.html.haml
  db/schema.rb
Labels: UConn

#1812 [#137479] Allow configuring a support email for top-level link
  app/views/shared/_header.html.haml
  app/views/shared/_support.html.haml
  config/locales/en.yml
  config/settings.yml
Labels: NU
