Repository tablexi/nucore-open, pull requests merged in 2018-04, with the labels that each got.

#1466 [#141105] keep existing filter params when sorting
  app/helpers/application_helper.rb
Labels: NU

#1467 [#140541] add a hint that reservation note visible to admins only
  app/views/reservations/_account_field.html.haml
  app/views/reservations/edit.html.haml
  config/locales/en.yml
Labels: RaDar

#1470 [#140980] Add Assigned User to export raw
  app/models/reports/export_raw.rb
  spec/models/reports/export_raw_spec.rb
Labels: NU

#1471 [#140361] refactor user creation/updating to use user form object (open)
  app/controllers/users_controller.rb
  app/forms/user_form.rb
  app/models/user.rb
  app/views/users/edit.html.haml
  app/views/users/new_external.html.haml
  spec/controllers/users_controller_spec.rb
  spec/features/admin/managing_user_spec.rb
Labels: RaDar

#1464 Fix cap deploy on stage
  app/controllers/api/order_details_controller.rb
  config/initializers/add_settings_overrides.rb
  config/initializers/devise.rb
  config/secrets.yml.template
  config/settings/development.yml
  config/settings/override.yml
  config/settings/stage.yml
  vendor/engines/secure_rooms/app/controllers/secure_rooms_api/api_controller.rb
  vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/events_controller_spec.rb
  vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
  vendor/engines/secure_rooms/spec/features/scanning_in_and_out_spec.rb
Labels: RaDar, UIC

#1472 bundle update parser, remove settings.local.yml from linked files
  Gemfile.lock
  config/deploy.rb
Labels: RaDar, UIC

#1457 [#140997] feature flag saml create/update user
  config/settings.yml
  vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
  vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
Labels: RaDar

#1468 [#140541] add user facing note for admin reservations
  app/assets/javascripts/app/calendar.js.coffee
  app/controllers/facility_reservations_controller.rb
  app/forms/admin_reservation_form.rb
  app/presenters/reservations/calendar_presenter.rb
  app/views/facility_reservations/_admin_reservation_fields.html.haml
  app/views/shared/timeline/_facility_tooltip.html.haml
  config/locales/en.models.yml
  db/migrate/20180330180908_add_user_note_to_reservations.rb
  db/schema.rb
  spec/app_support/reservations/rendering_spec.rb
Labels: RaDar

#1475 [#141334] Prevent errors on non-html 404s
  app/controllers/application_controller.rb
  spec/features/accessing_invalid_files_spec.rb
Labels: NU

#1480 [#140403] replace filtering disputed orders
  app/controllers/facilities_controller.rb
  app/views/facilities/disputed_orders.html.haml
  app/views/facility_notifications/index.html.haml
  spec/controllers/facilities_controller_spec.rb
  spec/features/admin/disputed_orders_search_spec.rb
Labels: NU

#1483 include settings/stage.yml
  config/initializers/02_add_settings_overrides.rb
  config/initializers/add_settings_overrides.rb
Labels: RaDar, UIC

#1485 use i18n in routing for spec
  spec/features/accessing_invalid_files_spec.rb
Labels: RaDar

#1486 remove ordering clause that causes oracle compatibility issue
  app/controllers/facilities_controller.rb
  app/models/order_detail.rb
Labels: NU

#1481 [#73287] Add ability to suspend a user
  app/controllers/reports/reports_controller.rb
  app/controllers/users_controller.rb
  app/inputs/transaction_chosen2_input.rb
  app/models/order_detail.rb
  app/models/reports/export_raw.rb
  app/models/user.rb
  app/presenters/order_detail_journal_description_presenter.rb
  app/presenters/users/name_presenter.rb
  app/services/transaction_search/account_owner_searcher.rb
  app/services/transaction_search/ordered_for_searcher.rb
  app/support/statement_pdf.rb
  app/views/accounts/_member_table.html.haml
  app/views/accounts/_suspend_button.html.haml
  app/views/product_users/_table.html.haml
  app/views/search/_account_account_user_link.html.haml
  app/views/search/_facility_account_account_user_link.html.haml
  app/views/search/_global_user_role_link.html.haml
  app/views/search/_map_user_link.html.haml
  app/views/search/_user_new_account_link.html.haml
  app/views/search/_user_price_group_member_link.html.haml
  app/views/search/_user_product_approval_link.html.haml
  app/views/users/show.html.haml
  config/locales/en.models.yml
  config/locales/en.yml
  config/locales/views/admin/en.search.yml
  config/routes.rb
  db/migrate/20180406211501_rename_user_deactivated_at_to_suspended_at.rb
  db/schema.rb
  spec/controllers/devise/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/users.rb
  spec/features/admin/suspending_a_user_spec.rb
  spec/lib/ability_spec.rb
  spec/models/user_spec.rb
  spec/presenters/users/name_presenter_spec.rb
  vendor/engines/bulk_email/spec/services/bulk_email/recipient_searcher_spec.rb
  vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
  vendor/engines/secure_rooms/app/views/secure_rooms/shared/_secure_rooms_dashboard.html.haml
Labels: NU

#1494 [#141446] Fix display issue with "X" in chosen selectors
  app/assets/stylesheets/application.scss
Labels: NU

#1493 Remove old action and routes
  app/controllers/facility_accounts_controller.rb
  app/controllers/search_controller.rb
  app/views/admin/shared/_tabnav_account.html.haml
  app/views/facility_accounts/search.html.haml
  app/views/facility_accounts/search_results.html.haml
  app/views/facility_accounts/user_accounts.html.haml
  app/views/facility_accounts/user_search.html.haml
  app/views/search/_user_accounts_link.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/facility_accounts_controller_spec.rb
  spec/controllers/search_controller_spec.rb
Labels: NU

#1495 [#140404] Replace filtering in journals/statements tabs
  app/controllers/facility_journals_controller.rb
  app/controllers/facility_statements_controller.rb
  app/views/facility_journals/index.html.haml
  app/views/facility_journals/new.html.haml
  app/views/facility_statements/new.html.haml
  config/locales/en.yml
  spec/controllers/facility_journals_controller_spec.rb
  spec/controllers/facility_statements_controller_spec.rb
  spec/features/admin/facility_journals_search_spec.rb
  spec/features/admin/facility_statements_search_spec.rb
Labels: NU

#1478 [#140407] Reservation calendar drag and drop
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/app/calendar.js.coffee
  app/assets/javascripts/app/manage_orders.coffee
  app/assets/javascripts/app/reservation_calendar.js
  app/assets/javascripts/app/reservation_time_field_adjustor.js.coffee
  app/assets/javascripts/application.js
  app/assets/javascripts/calendar/fullcalendar.min.js
  app/assets/javascripts/reservations.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/calendar/fullcalendar.extensions.scss
  app/controllers/reservations_controller.rb
  app/helpers/reservations_helper.rb
  app/presenters/reservations/calendar_presenter.rb
  app/presenters/schedule_rule_calendar_presenter.rb
  app/views/facility_reservations/edit.html.haml
  app/views/facility_reservations/show.html.haml
  app/views/reservations/_js_variables.html.haml
  app/views/reservations/edit.html.haml
  app/views/reservations/new.html.haml
  app/views/schedule_rules/index.html.haml
  app/views/shared/headers/_calendar.html.haml
  config/locales/en.yml
  config/settings.yml
  spec/app_support/reservations/rendering_spec.rb
  spec/controllers/reservations_controller_spec.rb
  spec/helpers/date_helper_spec.rb
  spec/models/reservation_spec.rb
  spec/rails_helper.rb
  vendor/assets/stylesheets/calendar/fullcalendar.scss
  vendor/engines/fullcalendar/.gitignore
  vendor/engines/fullcalendar/README.md
  vendor/engines/fullcalendar/Rakefile
  vendor/engines/fullcalendar/fullcalendar.gemspec
  vendor/engines/fullcalendar/lib/fullcalendar.rb
  vendor/engines/fullcalendar/lib/fullcalendar/engine.rb
  vendor/engines/fullcalendar/lib/fullcalendar/version.rb
  vendor/engines/fullcalendar/vendor/assets/javascripts/fullcalendar.js
  vendor/engines/fullcalendar/vendor/assets/stylesheets/fullcalendar.css
Labels: NU

#1502 [#141487] replace filtering for my transactions in review
  app/controllers/transactions_controller.rb
  app/views/shared/transactions/_in_review.html.haml
  spec/controllers/transactions_controller_spec.rb
  spec/features/transactions_search_spec.rb
Labels: NU

#1504 Fix missing translations and enable raising in errors in test/CI
  app/views/users/show.html.haml
  config/environments/test.rb
  config/locales/en.account_components.yml
  config/locales/en.yml
Labels: NU

#1505 [#140406] Remove old filtering code
  .haml-lint_todo.yml
  .rubocop_todo.yml
  app/controllers/accounts_controller.rb
  app/controllers/facilities_controller.rb
  app/controllers/facility_journals_controller.rb
  app/controllers/facility_notifications_controller.rb
  app/controllers/facility_statements_controller.rb
  app/controllers/transactions_controller.rb
  app/inputs/transaction_chosen2_input.rb
  app/inputs/transaction_chosen_input.rb
  app/inputs/transaction_chosen_old_input.rb
  app/views/facilities/disputed_orders.html.haml
  app/views/facilities/movable_transactions.html.haml
  app/views/facilities/transactions.html.haml
  app/views/facility_accounts_reconciliation/index.html.haml
  app/views/facility_journals/new.html.haml
  app/views/facility_notifications/in_review.html.haml
  app/views/facility_notifications/index.html.haml
  app/views/facility_orders/index.html.haml
  app/views/facility_orders/show_problems.html.haml
  app/views/facility_reservations/index.html.haml
  app/views/facility_reservations/show_problems.html.haml
  app/views/facility_statements/new.html.haml
  app/views/shared/transactions/_in_review.html.haml
  app/views/shared/transactions/_search.html.haml
  app/views/shared/transactions/_search2.html.haml
  app/views/shared/transactions/_top.html.haml
  app/views/shared/transactions/_top2.html.haml
  app/views/transactions/index.html.haml
  config/locales/en.controllers.yml
  lib/transaction_search.rb
  spec/controllers/accounts_controller_spec.rb
  spec/controllers/facilities_controller_spec.rb
  spec/controllers/facility_journals_controller_spec.rb
  spec/controllers/facility_statements_controller_spec.rb
  spec/lib/transaction_history_search_spec.rb
  spec/transaction_search_shared_examples.rb
  spec/transaction_search_spec_helper.rb
  vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_fields.html.haml
  vendor/engines/projects/lib/projects/engine.rb
  vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
  vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/show_problems.html.haml
Labels: NU

#1511 [#140001] update logo
  app/assets/images/logo.jpg
  app/assets/stylesheets/nucore.scss
Labels: NU

#1510 [#137478] add hint for reservation duration field
  app/views/reservations/_reservation_fields.html.haml
  config/locales/views/en.reservations.yml
Labels: NU

#1520 [#139182] update placeholder text
  app/inputs/transaction_chosen_old_input.rb
Labels: NU

#1515 [#140938] add specs to ensure case-insensitive matching
  vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
Labels: RaDar

#1523 [#141580] [#137466] Fixes from full calendar changes
  app/assets/javascripts/schedule_rules.js
  app/views/reservations/edit.html.haml
Labels: NU

#1524 [#137478] update hint text
  config/locales/views/en.reservations.yml
Labels: NU

#1525 Fix "create & start" when adjusting from calendar
  app/assets/javascripts/app/reservation_create_and_start.coffee
  app/assets/javascripts/app/reservations.coffee
  app/views/reservations/new.html.haml
Labels: NU

#1529 enforce feature setting on for suspending a user spec
  spec/features/admin/suspending_a_user_spec.rb
Labels: UIC

#1532 [#141677] fix csv export error when module is not included
  app/controllers/facilities_controller.rb
  app/controllers/transactions_controller.rb
Labels: NU

#1534 Rails 4 compatible 5.0 prep
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/models/order_import.rb
  app/presenters/view_hook.rb
  app/views/facility_journals/_problem_transactions.html.haml
  app/views/facility_orders/index.html.haml
  app/views/facility_orders/show_problems.html.haml
  app/views/facility_reservations/index.html.haml
  app/views/facility_reservations/show_problems.html.haml
  app/views/shared/transactions/_table.html.haml
  spec/helpers/view_hook_helper_spec.rb
  spec/models/instrument_spec.rb
  spec/models/journal_spec.rb
  spec/models/order_import_spec.rb
  spec/models/price_policy_spec.rb
  vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb
  vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
  vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
  vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/show_problems.html.haml
Labels: UIC
