Repository tablexi/nucore-open, pull requests merged in 2018-08, with the labels that each got.

#1644 Disable editing of recharge chart strings
  app/controllers/facility_facility_accounts_controller.rb
  app/forms/facility_account_form.rb
  app/models/account.rb
  app/models/facility_account.rb
  app/models/order_detail.rb
  app/views/facility_facility_accounts/_facility_account_fields.html.haml
  app/views/facility_facility_accounts/edit.html.haml
  app/views/facility_facility_accounts/index.html.haml
  app/views/shared/_account_fields.html.haml
  config/locales/views/admin/en.facility_facility_accounts.yml
  lib/validator/validator_factory.rb
  spec/controllers/facility_facility_accounts_controller_spec.rb
  spec/factories/facility_accounts.rb
  spec/models/instrument_for_cart_spec.rb
Labels: NU, RaDar

#1647 Refresh schema.rb for Rails 5.0
  db/schema.rb
Labels: Tech Task

#1210 Add instructions for loading a database dump into Oracle/Docker
  config/database.yml.oracle.template
  doc/HOWTO_oracle.md
  docker/oracle/setup.sql
Labels: NU

#1656 Update factory definitions
  spec/factories/accessories.rb
  spec/factories/account_users.rb
  spec/factories/accounts.rb
  spec/factories/external_services.rb
  spec/factories/facilities.rb
  spec/factories/facility_accounts.rb
  spec/factories/journals.rb
  spec/factories/nufs_accounts.rb
  spec/factories/order_details.rb
  spec/factories/orders.rb
  spec/factories/payments.rb
  spec/factories/price_groups.rb
  spec/factories/price_policies.rb
  spec/factories/products.rb
  spec/factories/relays.rb
  spec/factories/reservations.rb
  spec/factories/schedule_rules.rb
  spec/factories/stored_files.rb
  spec/factories/user_preferences.rb
  spec/factories/users.rb
Labels: Tech Task

#1657 Fix factory bot in engines
  Gemfile.lock
  spec/factories.rb
  vendor/engines/bulk_email/spec/factories/bulk_email/jobs.rb
  vendor/engines/c2po/spec/factories.rb
  vendor/engines/projects/spec/factories/projects.rb
  vendor/engines/sanger_sequencing/spec/factories/batches.rb
  vendor/engines/sanger_sequencing/spec/factories/product_groups.rb
  vendor/engines/secure_rooms/spec/factories/card_reader.rb
  vendor/engines/secure_rooms/spec/factories/event.rb
  vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb
  vendor/engines/split_accounts/spec/factories/split_accounts.rb
  vendor/engines/split_accounts/spec/factories/splits.rb
Labels: Tech Task

#1658 Upgrade Rubocop to 0.58
  .codeclimate.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
Labels: Tech Task, dependencies

#1659 [#143112] Enhance account price group member search results
  app/controllers/account_price_group_members_controller.rb
  app/views/account_price_group_members/search_results.html.haml
  spec/controllers/account_price_group_members_controller_spec.rb
  vendor/engines/c2po/spec/controllers/account_price_group_members_controller_spec.rb
Labels: RaDar

#1662 [#136049] Allow reservation cost to be overridden
  config/locales/en.models.yml
  spec/features/admin/manage_order_detail_spec.rb
Labels: RaDar

#1664 [#143112] Fix spec when account number is not valid
  spec/controllers/account_price_group_members_controller_spec.rb
Labels: RaDar, Tech Task

#1663 Fix some Rubocop issues
  .rubocop_todo.yml
  app/models/budgeted_chart_string.rb
  app/models/reports/instrument_unavailable_report.rb
  app/services/journal_row_builder.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/mail_logger.rb
  config/routes.rb
  db/migrate/20110403013939_add_order_detail_note.rb
  lib/csv_helper.rb
  lib/nucore.rb
  spec/controllers/order_management/order_details_controller_spec.rb
  spec/models/product_spec.rb
  spec/services/order_details/dispute_resolved_notifier_spec.rb
  spec/teaspoon_env.rb
  vendor/engines/split_accounts/spec/controllers/instrument_day_reports_controller_spec.rb
  vendor/engines/split_accounts/spec/models/split_account_spec.rb
Labels: Tech Task
