Repository tablexi/nucore-open, pull requests merged in 2019-01, with the labels that each got.

#1813 [#137686] Report an issue
  app/controllers/instrument_issues_controller.rb
  app/mailers/instrument_issue_mailer.rb
  app/models/facility.rb
  app/models/instrument_issue.rb
  app/models/user_role.rb
  app/presenters/reservation_user_action_presenter.rb
  app/views/instrument_issue_mailer/create.html.haml
  app/views/instrument_issue_mailer/create.text.erb
  app/views/instrument_issues/new.html.haml
  config/locales/views/en.instrument_issues.yml
  config/routes.rb
  lib/csv_array_string.rb
  spec/features/instrument_issues_spec.rb
  spec/mailers/previews/instrument_issue_mailer_preview.rb
  spec/models/facility_spec.rb
  spec/models/instrument_issue_spec.rb
  spec/presenters/reservation_user_action_presenter_spec.rb
  spec/rails_helper.rb
Labels: NU

#1823 [#137686] Improve "Report an Issue" wording
  config/locales/views/en.instrument_issues.yml
Labels: NU

#1822 Tech task: Fix sporadic test failure
  spec/controllers/product_users_controller_spec.rb
Labels: Tech Task

#1826 [#146242] Fix for split accounts when cancelled with a fee
  app/models/instrument_price_policy_calculations.rb
  vendor/engines/split_accounts/app/services/split_accounts/attribute_splitter.rb
  vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Labels: RaDar

#1832 Fix calculated_cost when missing reservation
  app/models/instrument_price_policy_calculations.rb
  spec/models/reports/export_raw_spec.rb
  vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Labels: RaDar

#1833 Only split calculated_cost when doing export raw
  app/models/reports/export_raw.rb
  vendor/engines/split_accounts/app/services/split_accounts/order_detail_list_transformer.rb
  vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb
  vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Labels: RaDar

#1830 [#137738] Total cost on pages
  app/assets/stylesheets/nucore.scss
  app/support/price_displayment.rb
  app/views/facilities/disputed_orders.html.haml
  app/views/facilities/movable_transactions.html.haml
  app/views/facilities/transactions.html.haml
  app/views/facility_notifications/in_review.html.haml
  app/views/facility_notifications/index.html.haml
  app/views/facility_statements/new.html.haml
  app/views/shared/transactions/_table.html.haml
  app/views/shared/transactions/_table_inside.html.haml
  app/views/transactions/index.html.haml
  config/locales/en.yml
  spec/features/admin/review_period_spec.rb
Labels: NU

#1824 Tech task: Clean up Account -> Facility relationship
  app/models/account.rb
  vendor/engines/c2po/app/models/credit_card_account.rb
  vendor/engines/c2po/app/models/purchase_order_account.rb
Labels: RaDar

#1829 [#144419] Make Account-Facility relationship Many-to-Many
  app/models/account.rb
  app/models/account_facility_join.rb
  db/migrate/20190104011154_change_account_facility_relationship_144419.rb
  db/schema.rb
  spec/affiliate_account_helper.rb
  spec/support/shared_examples/account_shared_examples.rb
  spec/support/shared_examples/affiliate_account_shared_examples.rb
  vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
  vendor/engines/c2po/spec/models/credit_card_account_spec.rb
  vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
  vendor/engines/split_accounts/app/models/split_accounts/account_extension.rb
  vendor/engines/split_accounts/app/models/split_accounts/split.rb
Labels: RaDar

#1836 Account facility rename single cross methods
  app/models/account.rb
  app/models/account_config.rb
  app/services/account_builder.rb
  app/views/shared/_statements_table.html.haml
  spec/models/account_config_spec.rb
  spec/models/nufs_account_spec.rb
  vendor/engines/c2po/spec/models/credit_card_account_spec.rb
  vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
Labels: RaDar

#1838 [#144300] Add account select to Add to Order form
  app/controllers/facility_orders_controller.rb
  app/forms/add_to_order_form.rb
  app/helpers/accounts_helper.rb
  app/models/account.rb
  app/models/order.rb
  app/views/facility_facility_accounts/index.html.haml
  app/views/facility_orders/_merge_order_form.html.haml
  config/locales/en.yml
  config/locales/forms/en.add_to_order_form.yml
  spec/app_support/order_row_importer_spec.rb
  spec/controllers/facility_orders_controller_spec.rb
  spec/features/admin/adding_to_an_order_spec.rb
Labels: NU

#1840 [#144419] Interface for managing an Account's facilities
  app/assets/stylesheets/nucore.scss
  app/controllers/account_facility_joins_controller.rb
  app/forms/account_facility_joins_form.rb
  app/models/account.rb
  app/services/account_builder.rb
  app/views/account_facility_joins/edit.html.haml
  app/views/accounts/index.html.haml
  app/views/admin/shared/_tabnav_payment_method.html.haml
  config/locales/en.controllers.yml
  config/locales/en.models.yml
  config/locales/en.yml
  config/locales/views/en.accounts.yml
  config/routes.rb
  config/settings.yml
  spec/features/admin/account_facility_joins_controller_spec.rb
Labels: RaDar

#1847 Add spec for timed services in export raw
  spec/factories/price_policies.rb
  spec/models/reports/export_raw_spec.rb
  spec/support/helper_methods.rb
Labels: RaDar

#1849 Tech task: Fix spec for export raw price calculation.
  spec/models/reports/export_raw_spec.rb
Labels: RaDar

#1850 Tech task: Fix feature-flag dependent specs
  spec/controllers/instruments_controller_spec.rb
  spec/controllers/reservations_controller_spec.rb
  spec/features/admin/account_facility_joins_controller_spec.rb
  spec/features/admin/managing_training_requests_spec.rb
  spec/features/admin/managing_user_spec.rb
  spec/features/admin/product_notifications_controller_spec.rb
  spec/features/admin/suspending_a_user_spec.rb
  spec/features/my_files_spec.rb
  spec/features/passwords_spec.rb
  spec/models/product_for_cart_spec.rb
  spec/services/results_file_notifier_spec.rb
  vendor/engines/bulk_email/spec/features/bulk_emailer_searching_spec.rb
Labels: UIC
