Repository tablexi/nucore-open, pull requests merged in 2019-02, with the labels that each got.

#1859 [#144419] Improve PO description if it's part of more than one facility
  vendor/engines/c2po/app/models/purchase_order_account.rb
  vendor/engines/c2po/config/locales/en.yml
  vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
Labels: RaDar

#1861 [#144300] Rearrange payment source dropdown on add to order
  app/assets/stylesheets/nucore.scss
  app/views/facility_orders/_merge_order_form.html.haml
Labels: NU

#1862 [#144524] Fix red select text in Firefox
  app/assets/stylesheets/nucore.scss
Labels: RaDar

#1868 Show all facilities for account in user listing
  app/views/shared/_accounts_table.html.haml
  config/locales/en.yml
Labels: RaDar

#1873 [#142504] Add “Ordered For” Filter on Billing Pages and remove Facilities Filter
  app/controllers/facilities_controller.rb
  app/controllers/facility_journals_controller.rb
  app/controllers/facility_notifications_controller.rb
  app/controllers/facility_statements_controller.rb
  app/services/transaction_search/account_owner_searcher.rb
  app/services/transaction_search/account_searcher.rb
  app/services/transaction_search/base_searcher.rb
  app/services/transaction_search/facility_searcher.rb
  app/services/transaction_search/order_status_searcher.rb
  app/services/transaction_search/ordered_for_searcher.rb
  app/services/transaction_search/product_searcher.rb
  app/services/transaction_search/searcher.rb
Labels: NU

#1874 [#147749] Add product-specific recipients for "Report an Issue"
  app/controllers/product_notifications_controller.rb
  app/models/instrument.rb
  app/models/instrument_issue.rb
  app/views/product_notifications/edit.html.haml
  app/views/product_notifications/show.html.haml
  config/locales/en.models.yml
  config/locales/views/admin/en.product_notifications.yml
  db/migrate/20190220001838_add_issue_report_recipients_to_product.rb
  db/schema.rb
  spec/models/instrument_issue_spec.rb
  spec/models/instrument_spec.rb
Labels: NU

#1880 [#144828] Use database for setting product boolean defaults
  app/models/product.rb
  db/migrate/20190227031006_fix_product_defaults.rb
  db/schema.rb
Labels: NU, Tech Task
