Repository tablexi/nucore-open, pull requests merged in 2020-03, with the labels that each got.

#2229 [#152924] Prevent error when updating order with auto-scaled accessories
  app/controllers/order_management/order_details_controller.rb
  config/locales/en.controllers.yml
  config/locales/views/admin/en.order_management.yml
  spec/controllers/order_management/order_details_controller_spec.rb
Labels: NU

#2232 [#152933] Fix print styles on Formio embeds
  app/views/layouts/formio.html.haml
Labels: NU

#2231 Fix XLS journal spreadsheet rendering
  app/services/journals/journal_format.rb
  spec/services/journals/journal_format_spec.rb
Labels: UMass

#2209 [#140079] Improve product search (MySQL only)
  app/models/account.rb
  app/models/full_text_search/base_searcher.rb
  app/models/full_text_search/like_searcher.rb
  app/models/full_text_search/model.rb
  app/models/full_text_search/mysql_searcher.rb
  app/models/order_detail.rb
  app/models/product.rb
  app/models/user.rb
  app/services/global_search/order_searcher.rb
  app/services/global_search/product_searcher.rb
  db/migrate/20200211001831_add_full_text_index.rb
  db/schema.rb
  lib/nucore.rb
  lib/nucore/database.rb
  lib/nucore/database/case_sensitivity_helper.rb
  lib/nucore/database/sort_helper.rb
  lib/nucore/database/where_ids_in.rb
  spec/controllers/global_search_controller_spec.rb
  spec/models/full_text_search/mysql_searcher_spec.rb
  spec/services/global_search/product_searcher_spec.rb
Labels: Dartmouth

#2242 [#151208] Export Raw "Timed Services" enhancement
  app/models/timed_service_price_policy.rb
  spec/factories/price_policies.rb
  spec/models/reports/export_raw_spec.rb
Labels: NU

#2239 [#148698] Update instrument dashboard label
  app/views/facilities/_facility_fields.html.haml
  app/views/facilities/manage.html.haml
  config/locales/views/admin/en.facilities.yml
Labels: NU

#2238 [#38893] Fix ordering of product groups on facility homepage
  app/controllers/facilities_controller.rb
  app/models/product_display_group.rb
  spec/controllers/facilities_controller_spec.rb
  spec/models/product_display_group_spec.rb
Labels: NU

#2240 Fix circular dependency issue
  app/models/product.rb
Labels: Dartmouth

#2241 Tech task: Fix spurious spec failure
  spec/factories/users.rb
  spec/services/order_row_importer_spec.rb
  spec/system/admin/clones_account_memberships_spec.rb
  vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/events_controller_spec.rb
Labels: Dartmouth

#2246 [#149739] Fix sorting when deciding most recent order
  app/forms/add_to_order_form.rb
  spec/factories/order_details.rb
  spec/forms/add_to_order_form_spec.rb
Labels: NU

#2210 [#140079] Improve product search for Oracle
  Gemfile
  app/models/full_text_search/model.rb
  app/models/full_text_search/oracle_searcher.rb
  db/migrate/20200213005326_add_full_text_index_for_oracle.rb
  spec/models/full_text_search/oracle_searcher_spec.rb
Labels: Dartmouth, blocked

#2261 [#152869] Add user roles to audit logs
  app/controllers/facility_users_controller.rb
  app/controllers/global_user_roles_controller.rb
  app/models/facility.rb
  app/models/log_event.rb
  app/models/user_role.rb
  app/services/log_event_searcher.rb
  config/locales/views/admin/en.log_events.yml
  db/migrate/20200327163058_add_soft_delete_to_user_role.rb
  db/schema.rb
  spec/controllers/facility_users_controller_spec.rb
  spec/controllers/global_user_roles_controller_spec.rb
  spec/factories/user_roles.rb
  spec/models/log_event_spec.rb
  spec/models/user_role_spec.rb
  spec/services/log_event_searcher_spec.rb
Labels: NU
