Repository tablexi/nucore-open, pull requests merged in 2020-02, with the labels that each got.

#2194 [#144526] Add link to download results as zip file
  app/views/order_management/order_details/files.html.haml
  config/locales/en.yml
Labels: Dartmouth

#2196 Tech task: make seeds idempotent
  db/seeds.rb
Labels: UMass

#2199 [#139340] Fix location of search button on account search
  app/views/facility_accounts/index.html.haml
  app/views/facility_accounts/search_results.html.haml
Labels: NU

#2200 [#149133] Update send notifications text
  app/mailers/notifier.rb
  app/models/account.rb
  app/support/notification_sender.rb
  app/views/notifier/review_orders.html.haml
  app/views/notifier/review_orders.text.erb
  config/locales/en.notifier.yml
  spec/app_support/notification_sender_spec.rb
  spec/mailers/notifier_spec.rb
  spec/mailers/previews/notifier_preview.rb
  vendor/engines/c2po/app/models/purchase_order_account.rb
Labels: NU

#2198 [#148320] Improve performance of relay statuses
  app/controllers/instruments_controller.rb
  app/models/concerns/products/relay_support.rb
  app/models/instrument_status.rb
  app/models/power_relay.rb
  app/models/relay.rb
  app/services/instrument_status_fetcher.rb
  config/initializers/power_relay_logger.rb
  spec/controllers/instruments_controller_spec.rb
  spec/services/instrument_status_fetcher_spec.rb
Labels: NU

#2201 [#152761] Improve performance of occupancies dashboard
  vendor/engines/secure_rooms/app/controllers/secure_rooms/occupancies_controller.rb
  vendor/engines/secure_rooms/app/views/secure_rooms/occupancies/index.html.haml
  vendor/engines/secure_rooms/app/views/secure_rooms/shared/_secure_rooms_dashboard.html.haml
Labels: NU

#2193 [#149740] Add reference_id to OrderDetail
  app/controllers/facility_orders_controller.rb
  app/forms/add_to_order_form.rb
  app/models/reports/export_raw.rb
  app/models/reservation.rb
  app/services/order_detail_update_param_hash_extractor.rb
  app/services/order_details/param_updater.rb
  app/services/reservation_creator.rb
  app/views/facility_orders/_merge_order_form.html.haml
  app/views/order_management/order_details/_form.html.haml
  app/views/orders/_cart_row.html.haml
  app/views/reservations/new.html.haml
  config/locales/en.models.yml
  config/locales/forms/en.add_to_order_form.yml
  db/migrate/20200130153146_add_reference_id_to_order_details.rb
  db/schema.rb
  spec/controllers/facility_orders_controller_spec.rb
  spec/controllers/order_management/order_details_controller_spec.rb
  spec/features/placing_an_order_on_behalf_of_spec.rb
  spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
Labels: NU

#2212 Make formio layout more haml and add viewhook
  app/views/layouts/formio.html.haml
Labels: NU

#2213 [#148320] Fix caching issue with shared relays
  app/models/instrument_status.rb
  app/services/instrument_status_fetcher.rb
  spec/services/instrument_status_fetcher_spec.rb
Labels: NU

#2220 [#151885] Fixes for add to order on bulk upload
  app/support/order_row_importer.rb
  spec/models/order_import_csv_spec.rb
Labels: NU

#2222 [#152855] Properly filter unpurchased orders from movable
  app/models/order_detail.rb
  spec/models/order_detail_spec.rb
Labels: NU

#2221 [#152849] Fix movable transaction when order is missing costs
  app/views/shared/transactions/_table_inside.html.haml
  spec/system/admin/moving_transactions_spec.rb
Labels: NU

#2225 [#151885] Fixes for oracle on adding to bulk upload
  app/support/order_row_importer.rb
  spec/models/order_import_csv_spec.rb
Labels: NU

#2205 [#148698] Facility instruments dashboard
  app/assets/javascripts/dashboard_refresh.js
  app/controllers/facilities_controller.rb
  app/controllers/instruments_dashboard_controller.rb
  app/models/facility.rb
  app/models/reservation.rb
  app/views/admin/shared/_tabnav_order.html.haml
  app/views/admin/shared/_tabnav_reservation.html.haml
  app/views/facilities/_facility_fields.html.haml
  app/views/facilities/manage.html.haml
  app/views/instruments_dashboard/_dashboard.html.haml
  app/views/instruments_dashboard/dashboard.html.haml
  app/views/instruments_dashboard/public_dashboard.html.haml
  config/locales/views/admin/en.facilities.yml
  config/locales/views/admin/en.tabnav.yml
  config/locales/views/en.instruments_dashboard.yml
  config/routes.rb
  db/migrate/20200207234415_add_facility_dashboard_key.rb
  db/schema.rb
  spec/controllers/instruments_dashboard_controller_spec.rb
  spec/models/facility_spec.rb
  spec/models/reservation_spec.rb
  vendor/engines/secure_rooms/app/views/secure_rooms/occupancies/index.html.haml
Labels: NU

#2207 [#149739] Maintain status/completion date after add to order
  app/forms/add_to_order_form.rb
  app/models/order_status.rb
  spec/forms/add_to_order_form_spec.rb
Labels: NU

#2211 [#137160] Reorganize Billing Sidebar and remove AR module
  app/controllers/facility_accounts_controller.rb
  app/views/admin/shared/_sidenav_billing.html.haml
  app/views/admin/shared/_sidenav_users.html.haml
  app/views/facility_accounts/_sidebar.html.haml
  app/views/facility_accounts/accounts_receivable.html.haml
  app/views/shared/sidenav_billing/_reconciliation.html.haml
  app/views/shared/sidenav_billing/_statements.html.haml
  config/locales/en.yml
  config/locales/views/admin/en.shared.yml
  config/locales/views/admin/en.sidenav_billing.yml
  config/routes.rb
  config/settings.yml
  spec/controllers/facility_accounts_controller_spec.rb
Labels: NU

#2195 [#136393] Clone account memberships
  app/assets/javascripts/_common.js
  app/assets/javascripts/app/checkbox_form.js
  app/controllers/clone_account_memberships_controller.rb
  app/services/account_membership_cloner.rb
  app/services/user_finder.rb
  app/views/clone_account_memberships/index.html.haml
  app/views/clone_account_memberships/new.html.haml
  app/views/clone_account_memberships/search.html.haml
  app/views/user_accounts/edit.html.haml
  app/views/user_accounts/show.html.haml
  config/locales/en.models.yml
  config/locales/views/admin/en.clone_account_memberships.yml
  config/routes.rb
  spec/services/account_membership_cloner_spec.rb
  spec/system/admin/clones_account_memberships_spec.rb
Labels: Dartmouth

#1863 [#144419] Drop accounts.facility_id column
  app/models/account.rb
  app/services/account_builder.rb
  db/migrate/20190201222556_remove_facility_id_from_accounts.rb
  db/schema.rb
  spec/app_support/notification_sender_spec.rb
  spec/controllers/facility_journals_controller_spec.rb
  spec/controllers/facility_statements_controller_spec.rb
  spec/factories/accounts.rb
  spec/factories/nufs_accounts.rb
  spec/mailers/notifier_spec.rb
  spec/models/journal_spec.rb
  spec/models/nufs_account_spec.rb
  spec/system/creating_a_journal_spec.rb
  vendor/engines/c2po/app/models/purchase_order_account.rb
  vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
  vendor/engines/c2po/spec/factories.rb
  vendor/engines/c2po/spec/models/credit_card_account_spec.rb
  vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
Labels: NU

#2206 Add support for UMass journaling
  app/controllers/facility_journals_controller.rb
  app/models/journal_row.rb
  app/services/converters/double_entry_order_detail_to_journal_row_attributes.rb
  app/services/converters/null_product_to_journal_row_attributes.rb
  app/services/converters/order_detail_to_journal_row_attributes.rb
  app/services/journal_row_builder.rb
  app/services/journals/default_journal_csv.rb
  app/services/journals/journal_format.rb
  app/views/facility_journals/_downloads.html.haml
  app/views/facility_journals/show.csv.erb
  app/views/facility_journals/show.html.haml
  config/settings.yml
  spec/controllers/facility_journals_controller_spec.rb
  spec/services/converters/order_detail_to_journal_row_attributes_spec.rb
  spec/services/journal_row_builder_spec.rb
  spec/support/contexts/default_journal_builder_context.rb
  vendor/engines/secure_rooms/spec/services/journal_row_builder_spec.rb
  vendor/engines/split_accounts/app/decorators/split_accounts/split_order_detail_decorator.rb
  vendor/engines/split_accounts/spec/services/journal_row_builder_spec.rb
Labels: UMass

#2208 [#152806] Prevent future Ordered/Fulfilled dates in bulk upload
  app/services/order_row_importer.rb
  config/locales/services/en.order_row_importer.yml
  spec/services/order_row_importer_spec.rb
Labels: NU

#2215 [#38893] Group Products on Homepage
  app/assets/javascripts/app/multi_select_helper.js
  app/assets/javascripts/app/multi_select_move_between.js
  app/assets/javascripts/app/multi_select_reorder.js
  app/assets/stylesheets/app/move_between_selects.scss
  app/assets/stylesheets/app/typography.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/nucore.scss
  app/controllers/facilities_controller.rb
  app/controllers/product_display_group_positions_controller.rb
  app/controllers/product_display_groups_controller.rb
  app/helpers/facilities_helper.rb
  app/models/facility.rb
  app/models/product.rb
  app/models/product_display_group.rb
  app/models/product_display_group_product.rb
  app/support/orders/item_adder.rb
  app/views/admin/shared/_sidenav_product.html.haml
  app/views/facilities/_product.html.haml
  app/views/facilities/_product_display_group.html.haml
  app/views/facilities/_product_list.html.haml
  app/views/facilities/show.html.haml
  app/views/product_display_group_positions/edit.html.haml
  app/views/product_display_groups/_form.html.haml
  app/views/product_display_groups/edit.html.haml
  app/views/product_display_groups/index.html.haml
  app/views/product_display_groups/new.html.haml
  config/locales/en.models.yml
  config/locales/en.yml
  config/locales/views/admin/en.product_display_groups.yml
  config/locales/views/en.facilities.yml
  config/routes.rb
  db/migrate/20200213205646_create_product_groups.rb
  db/migrate/20200215061232_add_display_order_to_product_display_group_products.rb
  db/schema.rb
  lib/ability.rb
  spec/controllers/facilities_controller_spec.rb
  spec/factories/product_display_groups.rb
  spec/helpers/facilities_helper_spec.rb
  spec/models/product_display_group_spec.rb
  spec/system/admin/product_display_groups_spec.rb
Labels: NU

#2230 Fix account cloner spec when running under oracle
  spec/services/account_membership_cloner_spec.rb
Labels: Dartmouth
