Repository tablexi/nucore-open, pull requests merged in 2020-08, with the labels that each got.

#2368 Tech task: Clean up capitalization of Nucore module
  app/models/journal_cutoff_date.rb
  app/services/admin_reservation_expirer.rb
  app/support/auto_canceler.rb
  app/support/journals/closer.rb
  db/migrate/20100528203109_order_details_add_and_remove_fields.rb
  db/migrate/20100708221022_remove_statement_id_from_order_details.rb
  db/migrate/20110729173029_change_vestal_versions.rb
  db/migrate/20120502223446_alter_journal_rows_remove_nu.rb
  db/migrate/20120510172358_add_bi_table.rb
  db/migrate/20120801223135_journal_rows_allow_null_account.rb
  db/migrate/20160415231343_clean_duplicate_reservations.rb
  db/migrate/20170112204251_increase_delayed_jobs_handler_capacity.rb
  db/migrate/20180907190857_fix_oracle_timestamps.rb
  db/migrate/20190104011154_change_account_facility_relationship_144419.rb
  db/migrate/20191114122118_move_ordered_at_to_order_detail.rb
  db/migrate/20200213005326_add_full_text_index_for_oracle.rb
  lib/nucore/database.rb
  spec/mailers/previews/cancelation_mailer_preview.rb
  spec/mailers/previews/instrument_issue_mailer_preview.rb
  spec/mailers/previews/notifier_preview.rb
  spec/mailers/previews/order_detail_dispute_mailer_preview.rb
  spec/mailers/previews/problem_order_mailer_preview.rb
  spec/mailers/previews/training_request_mailer_preview.rb
  spec/support/matchers/sql_matchers.rb
  vendor/engines/sanger_sequencing/db/migrate/20160519030413_create_sanger_sequencing_submissions.rb
  vendor/engines/sanger_sequencing/spec/mailers/previews/purchase_notifier_preview.rb
Labels: Tech task

#2371 Tech task: Move google analytics key out of constant into settings
  app/views/shared/_google.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/settings.yml
Labels: Tech task

#2370 Tech task: Fix changelog links to point to the PR
  CHANGELOG.md
Labels: Tech task

#2372 Upgrade devise_saml_authenticatable to 1.6.0
  Gemfile.lock
  vendor/engines/saml_authentication/lib/saml_authentication/attribute_map_resolver.rb
  vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
  vendor/engines/saml_authentication/lib/saml_authentication/engine.rb
  vendor/engines/saml_authentication/lib/saml_authentication/idp_entity_id_reader.rb
  vendor/engines/saml_authentication/lib/saml_authentication/model.rb
  vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
Labels: dependencies

#2369 Tech task: Add AASM dependency
  Gemfile
  Gemfile.lock
Labels: Tech task

#2379 [#153876] Fix dropdown options for price group members
  config/locales/views/admin/en.log_events.yml
Labels: NU

#2380 Tech task: Refactor 404/403 handling for non-HTML pages
  app/controllers/application_controller.rb
Labels: Tech task

#2376 Tech task: Lock ckeditor to < 5
  Gemfile
  Gemfile.lock
Labels: dependencies

#2375 Bump devise_ldap_authenticatable to 0.8.7
  Gemfile.lock
Labels: dependencies

#2378 Tech task: Update sanitizer configuration
  config/initializers/sanitized_allowed.rb
  config/initializers/sanitizer.rb
Labels: Tech task

#2377 Tech task: switch to newer prawn-rails library
  Gemfile
  Gemfile.lock
Labels: dependencies

#2374 Bump chosen-rails to 1.9
  Gemfile.lock
Labels: dependencies

#2384 [#154227] Properly handle commas in facility names when setting the "from" name in bulk email
  vendor/engines/bulk_email/app/mailers/bulk_email/mailer.rb
  vendor/engines/bulk_email/spec/mailers/bulk_email/mailer_spec.rb
Labels: Dartmouth

#2385 Update validation so it works properly with expense_accounts feature disabled
  app/models/product.rb
Labels: UConn

#2386 Tech task: Update journal row account validation to handle settings properly
  app/models/journal_row.rb
  spec/models/journal_row_spec.rb
Labels: UConn

#2358 Tech task: Docker updates
  .dockerignore
  Dockerfile
  Gemfile
  Gemfile.lock
  config/database.yml.mysql.template
  config/database.yml.oracle.template
  config/secrets.yml.template
  docker-compose.yaml
  vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
Labels: Tech task
