Repository tablexi/nucore-open, pull requests merged in 2020-01, with the labels that each got.

#2136 Allow longer revenue accounts
  app/views/facility_facility_accounts/_facility_account_fields.html.haml
  app/views/facility_facility_accounts/edit.html.haml
  app/views/facility_facility_accounts/new.html.haml
  db/migrate/20191219162724_increase_revenue_account_field_length.rb
  db/schema.rb
Labels: UMass

#2143 [#150353] Prevent error when calculating on non-purchasable price policies
  app/models/instrument_price_policy_calculations.rb
  spec/models/instrument_price_policy_calculations_spec.rb
Labels: Dartmouth

#2141 [#152079] Fix adding timed service bundle
  app/models/order_detail_observer.rb
  spec/models/order_detail_spec.rb
Labels: NU

#2134 Research safety refactors for UMass
  app/services/research_safety_always_certified_adapter.rb
  app/services/research_safety_certification_lookup.rb
  app/validators/order_research_safety_certification_validator.rb
  app/views/product_research_safety_certification_requirements/index.html.haml
  spec/features/admin/user_research_safety_certifications_controller_spec.rb
  spec/features/research_safety/placing_a_reservation_spec.rb
  spec/support/research_safety_test_helpers.rb
  spec/validators/order_research_safety_certification_validator_spec.rb
  vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/requires_research_safety_certifications_rule.rb
  vendor/engines/secure_rooms/spec/services/secure_rooms/check_access/research_safety_spec.rb
Labels: UMass

#2148 Remove constricting spec
  spec/models/stored_file_spec.rb
Labels: UMass

#2147 Allow longer expense accounts for products
  app/models/product.rb
  db/migrate/20200106194222_remove_limit_from_product_expense_account.rb
  db/schema.rb
  spec/models/product_spec.rb
Labels: UMass

#2152 Upgrade I18n to 1.7.1
  Gemfile.lock
  app/helpers/translation_helper.rb
  app/models/account.rb
  config/locales/en.models.yml
  config/locales/models/en.account.yml
Labels: dependencies

#2150 Add webmock
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: UMass

#2153 Fix forrmatting of Order Date on "My Orders"
  app/views/shared/_order_details_table.html.haml
Labels: NU

#2154 [#140480] Disable reconciliation note field on order detail modal
  app/services/order_details/param_updater.rb
  app/views/order_management/order_details/_form.html.haml
  app/views/order_management/order_details/_reconcile_note.html.haml
  spec/features/admin/manage_order_detail_spec.rb
Labels: NU

#2151 [#152343] Add auditing to bulk account deletion
  app/controllers/account_users_controller.rb
  app/controllers/facility_account_users_controller.rb
  app/controllers/user_accounts_controller.rb
  app/models/account_user.rb
  app/models/user.rb
  app/views/user_accounts/edit.html.haml
  spec/controllers/account_users_controller_spec.rb
  spec/controllers/facility_account_users_controller_spec.rb
  spec/controllers/user_accounts_controller_spec.rb
  spec/models/user_spec.rb
Labels: Dartmouth

#2161 Send ip_port to Synaccess driver
  Gemfile.lock
  app/models/concerns/products/relay_support.rb
  app/models/power_relay.rb
  lib/tasks/demo_seed.rake
  spec/files/relays/synaccess_rev_b_status.xml
  spec/models/relay_synaccess_rev_b_spec.rb
Labels: UMass

#2160 [#170607701] Add ability to customize IP Port
  app/controllers/products_common_controller.rb
  app/models/concerns/products/relay_support.rb
  app/models/power_relay.rb
  app/models/relay.rb
  app/views/instruments/_instrument_fields.html.haml
  app/views/instruments/_relay_manage.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  db/migrate/20200113094755_rename_port_to_outlet_on_relays.rb
  db/migrate/20200113131617_add_ip_port_to_relays.rb
  db/schema.rb
  lib/tasks/demo_seed.rake
  spec/controllers/instruments_controller_spec.rb
  spec/factories/relays.rb
  spec/files/relays/synaccess_rev_b_status.xml
  spec/models/power_relay_spec.rb
  spec/models/relay_spec.rb
  spec/models/relay_synaccess_rev_b_spec.rb
Labels: UMass

#2165 Fix recharge account editing
  app/views/facility_facility_accounts/edit.html.haml
  app/views/facility_facility_accounts/new.html.haml
  spec/features/admin/recharge_accounts_spec.rb
  spec/models/account_spec.rb
Labels: UMass

#2166 [#146482] Fix text for problem resolution fields in export raw
  app/models/reports/export_raw.rb
  spec/models/reports/export_raw_spec.rb
Labels: NU

#2163 [#139382] Add ability to include multiples of an instrument in a bundle
  app/models/bundle_product.rb
  app/support/orders/item_adder.rb
  spec/features/placing_an_order_spec.rb
Labels: NU

#2167 [#151885] Add ability to add to an existing order in bulk import
  app/support/order_row_importer.rb
  public/templates/bulk_import_template.csv
  spec/app_support/order_row_importer_spec.rb
  spec/models/order_import_spec.rb
Labels: NU

#2155 [#139340] Add ability to export account search results to CSV
  app/controllers/facility_accounts_controller.rb
  app/models/concerns/reports/csv_exporter.rb
  app/services/account_searcher.rb
  app/services/reports/account_search_csv.rb
  app/views/facility_accounts/search_results.html.haml
  config/locales/en.yml
  spec/controllers/facility_accounts_controller_spec.rb
  spec/services/reports/account_search_csv_spec.rb
Labels: NU

#2176 Update import script in Oracle readme
  doc/HOWTO_oracle.md
Labels: NU

#2175 [#152191] Search more fields in account search
  app/assets/javascripts/app/export_csv_report.coffee
  app/controllers/facility_accounts_controller.rb
  app/mailers/account_search_result_mailer.rb
  app/services/account_searcher.rb
  app/services/reports/account_search_csv.rb
  app/views/account_search_result_mailer/search_result.html.haml
  app/views/account_search_result_mailer/search_result.text.erb
  app/views/facility_accounts/index.html.haml
  app/views/facility_accounts/search_results.html.haml
  config/initializers/csv_renderer.rb
  config/locales/views/admin/en.account_search_result.yml
  spec/mailers/previews/account_search_result_mailer_preview.rb
  spec/services/account_searcher_spec.rb
Labels: Dartmouth

#2174 [#146482] Users should not be able to resolve if missing start time
  app/services/auto_expire_reservation.rb
  app/services/order_details/problem_resolution_policy.rb
  app/views/problem_reservations/edit.html.haml
  spec/features/fixing_a_problem_reservation_spec.rb
  spec/services/auto_expire_reservation_spec.rb
  spec/services/move_to_problem_queue_spec.rb
Labels: NU

#2164 [#139339] Add ability to bulk import timed services
  app/support/order_row_importer.rb
  spec/app_support/order_row_importer_spec.rb
Labels: NU
